language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run init
script:
  - npm run format
after_success:
  - if [ -n "$(git status --porcelain)" ]; then exit 0; fi
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git add -A
  - git commit -m "dev: format code"
  - git push "https://${GH_TOKEN}@github.com/webokio/webok.git" $TRAVIS_BRANCH > /dev/null 2>&1
