language: node_js
node_js:
  - lts/*
cache: npm
before_install:
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/webokio/webok.git > /dev/null 2>&1
  - git fetch
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH
install:
  - npm install
  - npm run boot -- --no-ci
  - npm run build:dev
  - npm run boot -- --no-ci
script:
  - npm run format
after_success:
  - git checkout package-lock.json
  - if [ $(git diff --name-only | wc -l) -eq 0 ]; then exit 0; fi
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git add -A
  - "git commit -m 'dev: format code'"
  - git push --set-upstream origin $TRAVIS_PULL_REQUEST_BRANCH
