language: node_js
node_js:
  - lts/*
cache: npm
install:
  - npm install
  - npm run boot -- --no-ci
  - npm run build:dev
  - npm run boot -- --no-ci
script:
  - npm run format
after_success:
  - git checkout package-lock.json
  - if [ $(git diff --name-only | wc -l) -eq 0 ]; then exit 0; fi
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote set-url origin https://${GH_TOKEN}@github.com/webokio/webok.git
  - git add -A
  - "git commit -m 'dev: format code'"
  - git push origin $TRAVIS_BRANCH
