language: node_js
node_js:
  - lts/*
cache: npm
install:
  - npm install
  - npm run build:dev
  - npm run boot -- --no-ci
script:
  - npm run format
after_success:
  - if [ $(git diff --name-only | wc -l) = 0 ]; then exit 0; fi
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git add -A
  - git commit -m "dev: format code"
  - git push "https://${GH_TOKEN}@github.com/webokio/webok.git" $TRAVIS_BRANCH > /dev/null 2>&1
