version: '3'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev_network
    environment:
      POSTGRES_DB: webok_dev
      POSTGRES_USER: webok_dev_user
      POSTGRES_PASSWORD: webok_dev_secret
    ports:
      - 5432:5432
volumes:
  postgres_dev_data:
networks:
  dev_network:
