version: '3'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: webok
      POSTGRES_USER: webok_user
      POSTGRES_PASSWORD: webok_secret
    ports:
      - ${DATABASE_PORT:-5432}:5432
volumes:
  postgres_data:
